/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quingestion;
import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author jedda
 */
public class Historique extends javax.swing.JFrame {

    /**
     * Creates new form Historique
     */
    boolean click=false;
    
    Connxion conn=new Connxion();
    Statement stm;
    ResultSet Rs;
    JFrame mainFrame;
    public Historique(JFrame frame) {
      initComponents();
      DefaultTableModel model=new DefaultTableModel();
      mainFrame=frame;
       
       
        model.addColumn("Quincaillerie");
        model.addColumn("Produit");
         model.addColumn("Date");
        model.addColumn("Quantite");
        

        try{
            stm=conn.ObtenirConnexion().createStatement();
            ResultSet Rs=stm.executeQuery("Select * from vente");
            while(Rs.next()){
                model.addRow(new Object[]{Rs.getString("quincaillerie"),Rs.getString("produit"),Rs.getString("date"),Rs.getString("quantite")});
            }
        }catch(Exception e){System.err.println(e);}
       tabVente.setModel(model);   
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabVente = new javax.swing.JTable();
        vende = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        element = new javax.swing.JComboBox<>();
        liste = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        valeur = new javax.swing.JComboBox<>();
        rech = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabVente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabVente);

        vende.setBackground(new java.awt.Color(255, 153, 0));
        vende.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        vende.setText("Liste globale");
        vende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendeActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 51, 204));
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("LES VENTES");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Type de recherche :");

        element.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        element.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "quincaillerie", "produit", "date", "quantite" }));
        element.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elementActionPerformed(evt);
            }
        });

        liste.setBackground(new java.awt.Color(0, 0, 255));
        liste.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        liste.setForeground(new java.awt.Color(255, 255, 255));
        liste.setText("valider");
        liste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeMouseClicked(evt);
            }
        });
        liste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Choisissez:");

        valeur.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        valeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valeurActionPerformed(evt);
            }
        });

        rech.setBackground(new java.awt.Color(0, 0, 255));
        rech.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        rech.setForeground(new java.awt.Color(255, 255, 255));
        rech.setText("OK");
        rech.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rechMouseClicked(evt);
            }
        });
        rech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Recherche ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(element, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(liste))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valeur, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rech))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(element, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valeur, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(liste, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rech))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(334, 334, 334))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(vende, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(vende, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeActionPerformed
        // TODO add your handling code here:
        click=true;
        DefaultComboBoxModel liste=new DefaultComboBoxModel();

        String attribut=element.getSelectedItem().toString();
        
        
        
        
        try{
            stm=conn.ObtenirConnexion().createStatement();
            ResultSet Rs=stm.executeQuery("Select "+attribut+" from vente ");
            while(Rs.next()){
                liste.addElement(Rs.getString(attribut));

            }
            valeur.setModel(liste);
        }catch(Exception e){System.err.println(e);}
    }//GEN-LAST:event_listeActionPerformed

    private void rechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechActionPerformed
        // TODO add your handling code here:
        if(click){
         DefaultTableModel model=new DefaultTableModel();
        String elmt=element.getSelectedItem().toString();

        String val=valeur.getSelectedItem().toString();
       
        
        model.addColumn("Quincaillerie");
        model.addColumn("Produit");
        model.addColumn("Date");
        model.addColumn("Quantite");
        
        

        try{
            stm=conn.ObtenirConnexion().createStatement();
            ResultSet Rs=stm.executeQuery("Select * from vente where "+elmt+"='"+val+"'");
            while(Rs.next()){
                model.addRow(new Object[]{Rs.getString("quincaillerie"),Rs.getString("produit"),Rs.getString("date"),Rs.getString("quantite")});
            }
        }catch(Exception e){System.err.println(e);}
        tabVente.setModel(model);}
        else  JOptionPane.showMessageDialog(null,"Validez dabord le type de recherche"); 
    }//GEN-LAST:event_rechActionPerformed

    private void elementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elementActionPerformed
        // TODO add your handling code here:
        click=false;
    }//GEN-LAST:event_elementActionPerformed

    private void vendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendeActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=new DefaultTableModel();

            model.addColumn("Quincaillerie");
        model.addColumn("Produit");
        model.addColumn("Date");
        model.addColumn("Quantite");
        

        try{
            stm=conn.ObtenirConnexion().createStatement();
            ResultSet Rs=stm.executeQuery("Select * from vente");
            while(Rs.next()){
                model.addRow(new Object[]{Rs.getString("quincaillerie"),Rs.getString("produit"),Rs.getString("date"),Rs.getString("quantite")});
            }
        }catch(Exception e){System.err.println(e);}
        tabVente.setModel(model);
        
    }//GEN-LAST:event_vendeActionPerformed

    private void valeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valeurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valeurActionPerformed
 
    private void listeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeMouseClicked
        // TODO add your handling code here:
         click = true; 
    }//GEN-LAST:event_listeMouseClicked

    private void rechMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rechMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rechMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        mainFrame.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> element;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton liste;
    private javax.swing.JButton rech;
    private javax.swing.JTable tabVente;
    private javax.swing.JComboBox<String> valeur;
    private javax.swing.JButton vende;
    // End of variables declaration//GEN-END:variables
}
